import { useParams, useNavigate } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

const ArtifactArticle = () => {
  const { categoryId, artifactId } = useParams();
  const navigate = useNavigate();

  const articleData = {
    'understanding-llms': {
      'how-llms-work': {
        title: 'Decoding the Engine: A Deep Dive into How Large Language Models Really Work',
        date: 'Nov 13, 2025',
        content: (
          <div className="prose prose-invert max-w-none text-gray-300 leading-relaxed">
            <p className="mb-6">
              Large Language Models (LLMs)—such as OpenAI's ChatGPT, Google Gemini, and Claude—are defining the current era of artificial intelligence. While AI is a broad umbrella term encompassing many fields like robotics and expert systems, <strong className="text-accent">LLMs lie within the specialized domain of deep learning</strong>, utilizing powerful deep neural networks. At their core, LLMs are a type of machine learning model designed specifically for natural language processing tasks, allowing them to understand and generate human-like text.
            </p>

            <p className="mb-6">
              Understanding how these complex programs can write code, generate poems, summarize articles, and chat requires looking beneath the surface at their fundamental function, architecture, and training process.
            </p>

            <hr className="border-gray-700 my-8" />

            <h2 className="text-2xl md:text-3xl font-bold text-accent mb-6 mt-8">The Core Principle: Next Word Prediction</h2>

            <p className="mb-6">
              The seemingly limitless capabilities of an LLM stem from one simple yet powerful idea: <strong className="text-accent">next word prediction</strong>. The model operates auto-regressively, constantly predicting the most likely next word (W<sub>T</sub>) based on the prior context (W<sub>1</sub>, W<sub>2</sub>, ... W<sub>T-1</sub>) using conditional probability. This is more than just autocompletion; it's about predicting the most likely word given the entire sentence's context.
            </p>

            <p className="mb-6">
              When you provide the model with context, such as "The capital of France is," the model <strong className="text-cyan-300">tokenizes</strong> the input, sends it to its internal architecture, and outputs a probability distribution of the most likely next words, from which the next word (e.g., Paris) is sampled.
            </p>

            <hr className="border-gray-700 my-8" />

            <h2 className="text-2xl md:text-3xl font-bold text-accent mb-6 mt-8">The Transformer Architecture: Decoder Only</h2>

            <p className="mb-6">
              The technical foundation for modern LLMs is the <strong className="text-accent">Transformer architecture</strong>, which was first introduced in the groundbreaking research paper <em>"Attention is All You Need"</em>. Initially, the Transformer consisted of two main components: the encoder and the decoder, designed for tasks like neural machine translation (e.g., translating English input processed by the encoder into French output generated by the decoder).
            </p>

            <p className="mb-6">
              However, in modern LLMs like those inspired by GPT (Generative Pre-training), the encoder part is omitted, and only the decoder component is used. This <strong className="text-cyan-300">decoder-only architecture</strong> is the "engine behind text generation", taking input text and predicting the next word to generate coherent and contextually relevant text.
            </p>

            <hr className="border-gray-700 my-8" />

            <h2 className="text-2xl md:text-3xl font-bold text-accent mb-6 mt-8">The Three Phases of Training</h2>

            <p className="mb-6">
              Before an LLM is deployed, it undergoes a meticulous, multi-stage training process:
            </p>

            <h3 className="text-xl md:text-2xl font-semibold text-cyan-300 mb-4 mt-6">1. Pre-training</h3>
            <p className="mb-6">
              This initial phase involves training the model on a massive, raw data set. This data is vast—terabytes in size and containing trillions of words harvested from books, documents, articles, journals, and the entire internet. This process creates the <strong className="text-accent">foundational model</strong> or <strong className="text-accent">base model</strong>, which is excellent at generating coherent text but is not yet ready to function as a chatbot.
            </p>

            <h3 className="text-xl md:text-2xl font-semibold text-cyan-300 mb-4 mt-6">2. Supervised Fine-tuning (SFT)</h3>
            <p className="mb-6">
              To transform the base model into a helpful assistant that can follow instructions, it undergoes fine-tuning. This phase uses carefully prepared data sets labeled by human annotators. These data sets are formatted using <strong className="text-accent">prompt templates</strong> that mimic real human-assistant conversations, often utilizing special tokens like <code className="text-cyan-300 bg-gray-800 px-2 py-1 rounded">system</code>, <code className="text-cyan-300 bg-gray-800 px-2 py-1 rounded">user</code>, <code className="text-cyan-300 bg-gray-800 px-2 py-1 rounded">assistant</code>, and the <strong className="text-accent">End of Sentence (EOS)</strong> token. Fine-tuning is highly customizable; models can be specifically trained using prepared data sets to enhance their reasoning ability (e.g., for solving math problems) or to respond in a specific persona (e.g., "Jack Sparrow style").
            </p>

            <h3 className="text-xl md:text-2xl font-semibold text-cyan-300 mb-4 mt-6">3. Preference Alignment</h3>
            <p className="mb-6">
              This is an advanced step where a <strong className="text-accent">reward model</strong> is introduced. The goal is to align the model's responses with human preferences. The LLM receives a higher reward for generating useful, aligned responses and a lower reward for poor responses, teaching the model over time what kind of outputs humans prefer.
            </p>

            <hr className="border-gray-700 my-8" />

            <h2 className="text-2xl md:text-3xl font-bold text-accent mb-6 mt-8">The Auto-Regressive Stream</h2>

            <p className="mb-6">
              When you ask an LLM a question, the input is wrapped in a <strong className="text-accent">prompt template</strong> before reaching the model. Because LLMs function in an auto-regressive manner, they generate only one token at a time. Once a token is generated, it is immediately sent back to the user (creating the "streaming response") and appended to the context.
            </p>

            <p className="mb-6">
              The model continues this loop of generating the next most likely token given the updated context until it produces a complete answer or encounters the special <strong className="text-accent">End of Sentence (EOS)</strong> token, which was added during the training phase, or reaches a predefined maximum token limit.
            </p>

            <div className="mt-8 p-6 bg-gray-800/40 border border-gray-700 rounded-lg">
              <h3 className="text-xl font-semibold text-cyan-300 mb-4">Key Takeaways</h3>
              <ul className="space-y-2 text-gray-300">
                <li className="flex items-start">
                  <span className="text-accent mr-2">▹</span>
                  <span>LLMs are deep learning models specialized for natural language processing</span>
                </li>
                <li className="flex items-start">
                  <span className="text-accent mr-2">▹</span>
                  <span>Core principle: <strong>next word prediction</strong> using conditional probability</span>
                </li>
                <li className="flex items-start">
                  <span className="text-accent mr-2">▹</span>
                  <span>Modern LLMs use <strong>decoder-only Transformer architecture</strong></span>
                </li>
                <li className="flex items-start">
                  <span className="text-accent mr-2">▹</span>
                  <span>Three training phases: <strong>Pre-training</strong>, <strong>Supervised Fine-tuning</strong>, and <strong>Preference Alignment</strong></span>
                </li>
                <li className="flex items-start">
                  <span className="text-accent mr-2">▹</span>
                  <span>LLMs generate text <strong>auto-regressively</strong>, one token at a time</span>
                </li>
                <li className="flex items-start">
                  <span className="text-accent mr-2">▹</span>
                  <span>Special tokens like EOS control when generation stops</span>
                </li>
              </ul>
            </div>
          </div>
        ),
      },
      'temperature-in-llm': {
        title: 'Decoding the Randomness: How Temperature, Top K, and Top P Control AI Creativity',
        date: 'Nov 13, 2025',
        content: (
          <div className="prose prose-invert max-w-none text-gray-300 leading-relaxed">
            <p className="mb-6">
              Have you ever asked an AI chatbot the same question twice only to receive two different answers? This variability, or randomness, in the response generation of Large Language Models (LLMs) is controlled by specialized sampling techniques used during inference. Understanding these techniques -- especially <strong className="text-accent">Temperature</strong>, <strong className="text-accent">Top K</strong>, and <strong className="text-accent">Top P</strong> -- is key to mastering AI output.
            </p>

            <p className="mb-6">
              When generating text, an LLM processes the input prompt and produces raw logits for the next token. The softmax function is applied to these logits to create a probability distribution for all possible next tokens, and the choice made from this distribution heavily influences the entire generation process.
            </p>

            <p className="mb-6">
              One simple, but often limiting, approach is <strong className="text-cyan-300">greedy sampling</strong>, which always selects the token with the highest probability, making the response highly deterministic. While the response is always the same given the same context, outputs tend to be "boring repetitive and not very creative," meaning greedy sampling is generally avoided for chat bots.
            </p>

            <hr className="border-gray-700 my-8" />

            <h2 className="text-2xl md:text-3xl font-bold text-accent mb-6 mt-8">Temperature Scaling: Adjusting the Certainty</h2>

            <p className="mb-6">
              A crucial factor influencing randomness is <strong className="text-accent">temperature scaling</strong>. Before applying the softmax function to the raw logits, we scale them by a positive temperature value.
            </p>

            <p className="mb-4">
              By default, the temperature value is one. Changing this value dramatically affects the final probability distribution:
            </p>

            <ul className="list-disc list-inside mb-6 space-y-3 ml-4">
              <li>
                <strong className="text-accent">Low Temperature</strong> (less than one/close to zero): Makes responses more deterministic and less random. This causes the token with the highest logit to dominate the selection, leading to more confident and certain responses. Lower temperatures are better for factual writing.
              </li>
              <li>
                <strong className="text-accent">High Temperature</strong> (greater than one): Flattens the distribution. The probability of less likely tokens increases, while the probability of the most likely token decreases, making responses more random and creative. A slightly higher temperature is preferred for creative writing tasks, such as essays or stories.
              </li>
            </ul>

            <p className="mb-6">
              If the temperature is increased to an extreme value, the distribution becomes almost uniform, meaning random sampling could pick any token with equal chance. However, setting the temperature too high can degrade the quality, potentially causing the model to produce inaccurate or nonsensical outputs, leading most LLM providers to limit the usable range (often between zero and two).
            </p>

            <hr className="border-gray-700 my-8" />

            <h2 className="text-2xl md:text-3xl font-bold text-accent mb-6 mt-8">Filtering the Token Pool: Top K and Top P</h2>

            <p className="mb-6">
              Temperature scaling changes the probabilities, but <strong className="text-accent">Top K</strong> and <strong className="text-accent">Top P</strong> sampling limit which tokens are considered for selection.
            </p>

            <h3 className="text-xl md:text-2xl font-semibold text-cyan-300 mb-4 mt-6">1. Top K Sampling</h3>
            <p className="mb-6">
              This method limits the candidate tokens by selecting only the top K tokens with the highest probability values. If a K value of five is chosen, the model only samples from the five most probable tokens.
            </p>

            <h3 className="text-xl md:text-2xl font-semibold text-cyan-300 mb-4 mt-6">2. Top P (Nucleus) Sampling</h3>
            <p className="mb-6">
              This technique dynamically filters the tokens based on a cumulative probability threshold. Tokens are arranged in descending order of probability, and only those whose cumulative probability sums up to the specified Top P threshold (or slightly more) are included. For instance, setting Top P to 0.9 means collecting tokens until their combined probability reaches 90%. Setting Top P to zero is essentially the same as greedy sampling, considering only the highest probability token, while setting it to one includes the entire distribution.
            </p>

            <hr className="border-gray-700 my-8" />

            <h2 className="text-2xl md:text-3xl font-bold text-accent mb-6 mt-8">Bringing It All Together</h2>

            <p className="mb-6">
              These strategies are often used in combination, where logits are first scaled by the temperature value, and then Top K and Top P filtering are applied to further refine the set of available tokens before the next token is finally sampled. Together, <strong className="text-accent">Temperature</strong>, <strong className="text-accent">Top K</strong>, and <strong className="text-accent">Top P</strong> help strike a critical balance between making the generated text sound creative and natural or keeping it focused and safe.
            </p>

            <div className="mt-8 p-6 bg-gray-800/40 border border-gray-700 rounded-lg">
              <h3 className="text-xl font-semibold text-cyan-300 mb-4">Key Takeaways</h3>
              <ul className="space-y-2 text-gray-300">
                <li className="flex items-start">
                  <span className="text-accent mr-2">▹</span>
                  <span><strong>Temperature</strong> controls the randomness of outputs by scaling probability distributions</span>
                </li>
                <li className="flex items-start">
                  <span className="text-accent mr-2">▹</span>
                  <span><strong>Low temperature</strong> = more deterministic, factual responses</span>
                </li>
                <li className="flex items-start">
                  <span className="text-accent mr-2">▹</span>
                  <span><strong>High temperature</strong> = more creative, diverse outputs</span>
                </li>
                <li className="flex items-start">
                  <span className="text-accent mr-2">▹</span>
                  <span><strong>Top K</strong> limits selection to K most probable tokens</span>
                </li>
                <li className="flex items-start">
                  <span className="text-accent mr-2">▹</span>
                  <span><strong>Top P</strong> dynamically selects tokens based on cumulative probability</span>
                </li>
                <li className="flex items-start">
                  <span className="text-accent mr-2">▹</span>
                  <span>Combining these techniques allows fine-tuned control over AI creativity vs. consistency</span>
                </li>
              </ul>
            </div>
          </div>
        ),
      },
    },
    'data-engineering': {},
  };

  const categoryTitles = {
    'understanding-llms': 'Understanding Large Language Models',
    'data-engineering': 'Data Engineering',
  };

  const article = articleData[categoryId]?.[artifactId];
  const categoryTitle = categoryTitles[categoryId];

  if (!article) {
    return (
      <div className="min-h-screen bg-gray-950 text-gray-200 flex items-center justify-center">
        <div className="text-center">
          <h1 className="text-4xl font-bold text-accent mb-4">Article Not Found</h1>
          <button
            onClick={() => navigate('/')}
            className="text-gray-400 hover:text-accent transition-colors"
          >
            Return to Portfolio
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-950 text-gray-200">
      <div className="max-w-4xl mx-auto px-6 py-20">
        {/* Back Button */}
        <button
          onClick={() => navigate(`/artifacts/${categoryId}`)}
          className="flex items-center gap-2 text-accent hover:text-cyan-300 transition-colors mb-8 group"
        >
          <ArrowLeft className="w-5 h-5 group-hover:-translate-x-1 transition-transform" />
          <span>Back to {categoryTitle}</span>
        </button>

        {/* Article Header */}
        <article>
          <h1 className="text-4xl md:text-5xl font-bold text-accent mb-4">
            {article.title}
          </h1>

          <p className="text-gray-400 mb-12">{article.date}</p>

          {/* Article Content */}
          {article.content}
        </article>
      </div>
    </div>
  );
};

export default ArtifactArticle;
